<Project Sdk="Microsoft.NET.Sdk">

  <!-- build props -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- packages -->
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="NJsonSchema" Version="11.3.2" />
    <PackageReference Include="NJsonSchema.CodeGeneration" Version="11.3.2" />
    <PackageReference Include="NJsonSchema.CodeGeneration.CSharp" Version="11.3.2" />
    <PackageReference Include="Terminal.Gui" Version="2.0.0-v2-develop.2329" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
  </ItemGroup>

  <!-- global usings -->
  <ItemGroup>
    <Using Include="System.Diagnostics" />
  </ItemGroup>

  <!-- dev / release app settings -->
  <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
    <!-- used when invoked by dotnet run (Debug build in intermediate language) -->
    <Content Include="appsettings-local.json" TargetPath="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup Condition=" '$(Configuration)' == 'Release' ">
    <!-- used when dotnet pubslish -->
    <Content Include="appsettings-release.json" TargetPath="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
